using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIBattleLoading)]
	public partial class UIBattleLoadingComponent : Entity
	{
		 public Slider EUI_Slider_Slider;
	}
}
