using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIMainMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_RectTransform_Head = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Head)).GetComponent<RectTransform>();
			 self.EUI_Button_Frame = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Frame)).GetComponent<Button>();
			 self.EUI_Image_Head = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Image_Head)).GetComponent<Image>();
			 self.EUI_Text_PlayerName = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_PlayerName)).GetComponent<Text>();
			 self.EUI_Text_CupNum = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_CupNum)).GetComponent<Text>();
			 self.EUI_Button_Set = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Set)).GetComponent<Button>();
			 self.EUI_Button_Mail = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Mail)).GetComponent<Button>();
			 self.EUI_Button_Friend = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Friend)).GetComponent<Button>();
			 self.EUI_Button_Hero = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Hero)).GetComponent<Button>();
			 self.EUI_Button_Pet = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Pet)).GetComponent<Button>();
			 self.EUI_Button_Zhanlin = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Zhanlin)).GetComponent<Button>();
			 self.EUI_Button_Skill = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Skill)).GetComponent<Button>();
			 self.EUI_Button_Bag = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Bag)).GetComponent<Button>();
			 self.EUI_RectTransform_Show = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Show)).GetComponent<RectTransform>();
			 self.EUI_Camera_ShowCamera = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Camera_ShowCamera)).GetComponent<Camera>();
			 self.EUI_Transform_ShowLeft = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Transform_ShowLeft)).GetComponent<Transform>();
			 self.EUI_Transform_ShowCenter = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Transform_ShowCenter)).GetComponent<Transform>();
			 self.EUI_Transform_ShowRight = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Transform_ShowRight)).GetComponent<Transform>();
			 self.EUI_RectTransform_Team = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Team)).GetComponent<RectTransform>();
			 self.EUI_RectTransform_TeamLeft = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_TeamLeft)).GetComponent<RectTransform>();
			 self.EUI_RectTransform_TeamRight = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_TeamRight)).GetComponent<RectTransform>();
			 self.EUI_Text_Diamond = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Diamond)).GetComponent<Text>();
			 self.EUI_Button_Diamond = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Diamond)).GetComponent<Button>();
			 self.EUI_Text_Coin = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Coin)).GetComponent<Text>();
			 self.EUI_Button_Coin = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Coin)).GetComponent<Button>();
			 self.EUI_Button_Active = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Active)).GetComponent<Button>();
			 self.EUI_Button_Task = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Task)).GetComponent<Button>();
			 self.EUI_Button_Shop = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Shop)).GetComponent<Button>();
			 self.EUI_Button_Rank = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Rank)).GetComponent<Button>();
			 self.EUI_Button_LimitGift = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_LimitGift)).GetComponent<Button>();
			 self.EUI_Button_Match = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Match)).GetComponent<Button>();
			 self.EUI_Button_Mode = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Mode)).GetComponent<Button>();
			 self.EUI_Text_Mode = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Mode)).GetComponent<Text>();
		}
	}
}
