using UnityEngine;
using UnityEngine.UI;
using SuperScrollView;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIServerListMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_LoopListView2_ServerList = this.referenceCollector.Get<GameObject>(nameof(self.EUI_LoopListView2_ServerList)).GetComponent<LoopListView2>();
			 self.EUI_LoopGridView_RegionGrid = this.referenceCollector.Get<GameObject>(nameof(self.EUI_LoopGridView_RegionGrid)).GetComponent<LoopGridView>();
			 self.EUI_Button_Close = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Close)).GetComponent<Button>();
		}
	}
}
