using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UILogin)]
	public partial class UILoginComponent : Entity
	{
		 public Button EUI_Button_Register;
		 public InputField EUI_InputField_Account;
		 public InputField EUI_InputField_Password;
		 public Button EUI_Button_Login;
	}
}
