using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIBattleMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_ETCJoystick_MoveJoystick = this.referenceCollector.Get<GameObject>(nameof(self.EUI_ETCJoystick_MoveJoystick)).GetComponent<ETCJoystick>();
		}
	}
}
