using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIRegister)]
	public partial class UIRegisterComponent : Entity
	{
		 public Button EUI_Button_Close;
		 public InputField EUI_InputField_Account;
		 public InputField EUI_InputField_Password;
		 public Button EUI_Button_Register;
	}
}
