using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UITip)]
	public partial class UITipComponent : Entity
	{
		 public RectTransform EUI_RectTransform_Tip1;
		 public Text EUI_Text_Content1;
	}
}
