using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIDoubleSelectMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_Text_Title = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Title)).GetComponent<Text>();
			 self.EUI_Text_Content = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Content)).GetComponent<Text>();
			 self.EUI_Button_Ok = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Ok)).GetComponent<Button>();
			 self.EUI_Text_Ok = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Ok)).GetComponent<Text>();
			 self.EUI_Button_Cancel = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Cancel)).GetComponent<Button>();
			 self.EUI_Text_Cancel = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Cancel)).GetComponent<Text>();
		}
	}
}
