using UnityEngine;
using UnityEngine.UI;
using SuperScrollView;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UISelectMap)]
	public partial class UISelectMapComponent : Entity
	{
		 public Button EUI_Button_Close;
		 public LoopGridView EUI_LoopGridView;
	}
}
