using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIMatchingMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_Button_Cancel = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Cancel)).GetComponent<Button>();
		}
	}
}
