using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIBattle)]
	public partial class UIBattleComponent : Entity
	{
		 public ETCJoystick EUI_ETCJoystick_MoveJoystick;
	}
}
