using UnityEngine;
using UnityEngine.UI;
using SuperScrollView;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UISelectMapMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_Button_Close = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Close)).GetComponent<Button>();
			 self.EUI_LoopGridView = this.referenceCollector.Get<GameObject>(nameof(self.EUI_LoopGridView)).GetComponent<LoopGridView>();
		}
	}
}
