using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UILoginMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_Button_Register = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Register)).GetComponent<Button>();
			 self.EUI_InputField_Account = this.referenceCollector.Get<GameObject>(nameof(self.EUI_InputField_Account)).GetComponent<InputField>();
			 self.EUI_InputField_Password = this.referenceCollector.Get<GameObject>(nameof(self.EUI_InputField_Password)).GetComponent<InputField>();
			 self.EUI_Button_Login = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Login)).GetComponent<Button>();
		}
	}
}
