using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIMatching)]
	public partial class UIMatchingComponent : Entity
	{
		 public Button EUI_Button_Cancel;
	}
}
