using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UITipMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_RectTransform_Tip1 = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Tip1)).GetComponent<RectTransform>();
			 self.EUI_Text_Content1 = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Content1)).GetComponent<Text>();
		}
	}
}
