using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIAGm)]
	public partial class UIAGmComponent : Entity
	{
		 public RectTransform EUI_RectTransform_Timer;
		 public RectTransform EUI_RectTransform_Fps;
		 public Text EUI_Text_Fps;
		 public RectTransform EUI_RectTransform_Delay;
		 public Text EUI_Text_DelayTime;
		 public Button EUI_Button_Gm;
		 public RectTransform EUI_RectTransform_Reload;
		 public Button EUI_Button_Reload;
	}
}
