using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIDoubleSelect)]
	public partial class UIDoubleSelectComponent : Entity
	{
		 public Text EUI_Text_Title;
		 public Text EUI_Text_Content;
		 public Button EUI_Button_Ok;
		 public Text EUI_Text_Ok;
		 public Button EUI_Button_Cancel;
		 public Text EUI_Text_Cancel;
	}
}
