using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UILoginSceneMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_Button_Enter = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Enter)).GetComponent<Button>();
			 self.EUI_Button_SelectServer = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_SelectServer)).GetComponent<Button>();
			 self.EUI_Image_ServerState = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Image_ServerState)).GetComponent<Image>();
			 self.EUI_Text_ServerName = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_ServerName)).GetComponent<Text>();
		}
	}
}
