using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UISingleSelect)]
	public partial class UISingleSelectComponent : Entity
	{
		 public Text EUI_Text_Title;
		 public Text EUI_Text_Content;
		 public Button EUI_Button_Ok;
		 public Text EUI_Text_Button;
	}
}
