using UnityEngine;
using UnityEngine.UI;
using SuperScrollView;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIServerList)]
	public partial class UIServerListComponent : Entity
	{
		 public LoopListView2 EUI_LoopListView2_ServerList;
		 public LoopGridView EUI_LoopGridView_RegionGrid;
		 public Button EUI_Button_Close;
	}
}
