using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	public partial class UIAGmMediator
	{
		public override void OnAutoBind()
		{
			 self.EUI_RectTransform_Timer = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Timer)).GetComponent<RectTransform>();
			 self.EUI_RectTransform_Fps = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Fps)).GetComponent<RectTransform>();
			 self.EUI_Text_Fps = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_Fps)).GetComponent<Text>();
			 self.EUI_RectTransform_Delay = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Delay)).GetComponent<RectTransform>();
			 self.EUI_Text_DelayTime = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Text_DelayTime)).GetComponent<Text>();
			 self.EUI_Button_Gm = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Gm)).GetComponent<Button>();
			 self.EUI_RectTransform_Reload = this.referenceCollector.Get<GameObject>(nameof(self.EUI_RectTransform_Reload)).GetComponent<RectTransform>();
			 self.EUI_Button_Reload = this.referenceCollector.Get<GameObject>(nameof(self.EUI_Button_Reload)).GetComponent<Button>();
		}
	}
}
