using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UILoginScene)]
	public partial class UILoginSceneComponent : Entity
	{
		 public Button EUI_Button_Enter;
		 public Button EUI_Button_SelectServer;
		 public Image EUI_Image_ServerState;
		 public Text EUI_Text_ServerName;
	}
}
