using UnityEngine;
using UnityEngine.UI;

namespace ET
{
	/// *************************************************************************************************
	/// The following code is automatically generated by EUI framework. Please do not modify it manually.
	/// *************************************************************************************************
	[UITag(UIType.UIMain)]
	public partial class UIMainComponent : Entity
	{
		 public RectTransform EUI_RectTransform_Head;
		 public Button EUI_Button_Frame;
		 public Image EUI_Image_Head;
		 public Text EUI_Text_PlayerName;
		 public Text EUI_Text_CupNum;
		 public Button EUI_Button_Set;
		 public Button EUI_Button_Mail;
		 public Button EUI_Button_Friend;
		 public Button EUI_Button_Hero;
		 public Button EUI_Button_Pet;
		 public Button EUI_Button_Zhanlin;
		 public Button EUI_Button_Skill;
		 public Button EUI_Button_Bag;
		 public RectTransform EUI_RectTransform_Show;
		 public Camera EUI_Camera_ShowCamera;
		 public Transform EUI_Transform_ShowLeft;
		 public Transform EUI_Transform_ShowCenter;
		 public Transform EUI_Transform_ShowRight;
		 public RectTransform EUI_RectTransform_Team;
		 public RectTransform EUI_RectTransform_TeamLeft;
		 public RectTransform EUI_RectTransform_TeamRight;
		 public Text EUI_Text_Diamond;
		 public Button EUI_Button_Diamond;
		 public Text EUI_Text_Coin;
		 public Button EUI_Button_Coin;
		 public Button EUI_Button_Active;
		 public Button EUI_Button_Task;
		 public Button EUI_Button_Shop;
		 public Button EUI_Button_Rank;
		 public Button EUI_Button_LimitGift;
		 public Button EUI_Button_Match;
		 public Button EUI_Button_Mode;
		 public Text EUI_Text_Mode;
	}
}
